2018-11-07 20:50:52 [signals_handler DEBUG] Receive django ready signal
2018-11-07 20:50:52 [signals_handler DEBUG]   - fresh all settings
2018-11-07 20:50:56 [signals_handler DEBUG] Receive django ready signal
2018-11-07 20:50:56 [signals_handler DEBUG]   - fresh all settings
2018-11-07 20:51:11 [basehttp INFO] "GET / HTTP/1.1" 302 0
2018-11-07 20:51:12 [basehttp INFO] "GET /users/login/?next=/ HTTP/1.1" 200 4188
2018-11-07 20:51:12 [basehttp INFO] "GET /static/css/bootstrap.min.css HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/css/font-awesome.min.css HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/css/plugins/toastr/toastr.min.css HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/css/plugins/sweetalert/sweetalert.css HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/css/style.css HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/css/plugins/datatables/datatables.min.css HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/css/plugins/vaildator/jquery.validator.css HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:51:12 [basehttp INFO] "GET /static/css/jumpserver.css HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/js/jquery-2.1.1.js HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/js/jumpserver.js HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/js/plugins/datatables/datatables.min.js HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/js/plugins/sweetalert/sweetalert.min.js HTTP/1.1" 304 0
2018-11-07 20:51:12 [basehttp INFO] "GET /static/img/logo.png HTTP/1.1" 304 0
2018-11-07 20:51:16 [basehttp INFO] "POST /users/login/?next=/ HTTP/1.1" 302 0
2018-11-07 20:51:16 [basehttp INFO] "GET / HTTP/1.1" 200 24891
2018-11-07 20:51:16 [basehttp INFO] "GET /static/img/avatar/admin.png HTTP/1.1" 304 0
2018-11-07 20:51:16 [basehttp INFO] "GET /static/img/logo-text.png HTTP/1.1" 304 0
2018-11-07 20:51:16 [basehttp INFO] "GET /static/js/plugins/toastr/toastr.min.js HTTP/1.1" 304 0
2018-11-07 20:51:17 [basehttp INFO] "GET /static/js/plugins/metisMenu/jquery.metisMenu.js HTTP/1.1" 304 0
2018-11-07 20:51:17 [basehttp INFO] "GET /static/css/patterns/header-profile.png HTTP/1.1" 304 0
2018-11-07 20:51:17 [basehttp INFO] "GET /static/js/inspinia.js HTTP/1.1" 304 0
2018-11-07 20:51:17 [basehttp INFO] "GET /static/js/plugins/echarts/echarts.js HTTP/1.1" 304 0
2018-11-07 20:51:17 [basehttp INFO] "GET /static/img/header-profile.png HTTP/1.1" 304 0
2018-11-07 20:51:17 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:51:17 [basehttp INFO] "GET /static/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 304 0
2018-11-07 20:51:17 [basehttp INFO] "GET /static/js/plugins/echarts/chart/line.js HTTP/1.1" 304 0
2018-11-07 20:51:17 [basehttp INFO] "GET /static/js/plugins/echarts/chart/pie.js HTTP/1.1" 304 0
2018-11-07 20:51:33 [basehttp INFO] "GET /sqlaudits/masterprivilege/ HTTP/1.1" 200 21801
2018-11-07 20:51:33 [basehttp INFO] "GET /static/css/plugins/select2/select2.min.css HTTP/1.1" 304 0
2018-11-07 20:51:33 [basehttp INFO] "GET /static/js/plugins/select2/select2.full.min.js HTTP/1.1" 304 0
2018-11-07 20:51:33 [basehttp INFO] "GET /static/js/jquery.form.min.js HTTP/1.1" 304 0
2018-11-07 20:51:33 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:51:34 [basehttp INFO] "GET /static/fonts/glyphicons-halflings-regular.woff HTTP/1.1" 304 0
2018-11-07 20:51:36 [basehttp INFO] "GET /sqlaudits/masternetwork/ HTTP/1.1" 200 21691
2018-11-07 20:51:37 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:51:38 [basehttp INFO] "GET /sqlaudits/masterprivilege/ HTTP/1.1" 200 21801
2018-11-07 20:51:38 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:51:40 [basehttp INFO] "GET /sqlaudits/masternetwork/ HTTP/1.1" 200 21691
2018-11-07 20:51:41 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:51:42 [basehttp INFO] "GET /sqlaudits/masteruser/ HTTP/1.1" 200 21788
2018-11-07 20:51:42 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:51:44 [basehttp INFO] "GET /sqlaudits/masterconfig/ HTTP/1.1" 200 21822
2018-11-07 20:51:44 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:51:44 [basehttp INFO] "GET /api/sqlaudits/v1/masterconfig/?_=1541595104499 HTTP/1.1" 200 464
2018-11-07 20:51:50 [basehttp INFO] "GET /sqlaudits/masterconfig/create/ HTTP/1.1" 200 13126
2018-11-07 20:51:51 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:51:56 [basehttp INFO] "GET /api/sqlaudits/v1/masterconfig/?_=1541595115985 HTTP/1.1" 200 464
2018-11-07 20:51:58 [basehttp INFO] "GET /sqlaudits/masteruser/ HTTP/1.1" 200 21788
2018-11-07 20:51:58 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:52:11 [log ERROR] Internal Server Error: /sqlaudits/masteruser/create/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 516, in bootstrap_field
    return render_field(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/forms.py", line 69, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/renderers.py", line 248, in __init__
    raise BootstrapError('Parameter "field" should contain a valid Django BoundField.')
bootstrap3.exceptions.BootstrapError: Parameter "field" should contain a valid Django BoundField.
2018-11-07 20:52:11 [basehttp ERROR] "GET /sqlaudits/masteruser/create/ HTTP/1.1" 500 173491
2018-11-07 20:52:12 [log WARNING] Not Found: /favicon.ico
2018-11-07 20:52:12 [basehttp WARNING] "GET /favicon.ico HTTP/1.1" 404 3754
2018-11-07 20:52:44 [basehttp INFO] "GET /sqlaudits/masterconfig/ HTTP/1.1" 200 21822
2018-11-07 20:52:45 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:52:45 [basehttp INFO] "GET /api/sqlaudits/v1/masterconfig/?_=1541595164989 HTTP/1.1" 200 464
2018-11-07 20:52:47 [basehttp INFO] "GET /users/profile/ HTTP/1.1" 200 20750
2018-11-07 20:52:47 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:52:52 [basehttp INFO] "GET /i18n/zh-hans/ HTTP/1.1" 302 0
2018-11-07 20:52:52 [basehttp INFO] "GET /users/profile/ HTTP/1.1" 200 20750
2018-11-07 20:52:52 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:53:39 [basehttp INFO] "GET /sqlaudits/masterconfig/ HTTP/1.1" 200 21822
2018-11-07 20:53:39 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:53:40 [basehttp INFO] "GET /api/sqlaudits/v1/masterconfig/?_=1541595219827 HTTP/1.1" 200 464
2018-11-07 20:53:42 [basehttp INFO] "GET /sqlaudits/masterconfig/3/update/ HTTP/1.1" 200 13174
2018-11-07 20:53:42 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:53:44 [basehttp INFO] "POST /sqlaudits/masterconfig/3/update/ HTTP/1.1" 302 0
2018-11-07 20:53:45 [basehttp INFO] "GET /sqlaudits/masterconfig/ HTTP/1.1" 200 22075
2018-11-07 20:53:45 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:53:45 [basehttp INFO] "GET /api/sqlaudits/v1/masterconfig/?_=1541595225266 HTTP/1.1" 200 464
2018-11-07 20:53:52 [basehttp INFO] "GET /sqlaudits/masterconfig/create/ HTTP/1.1" 200 13126
2018-11-07 20:53:52 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:53:55 [basehttp INFO] "GET /sqlaudits/masteruser/ HTTP/1.1" 200 21788
2018-11-07 20:53:55 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:53:57 [log ERROR] Internal Server Error: /sqlaudits/masteruser/create/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 516, in bootstrap_field
    return render_field(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/forms.py", line 69, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/renderers.py", line 248, in __init__
    raise BootstrapError('Parameter "field" should contain a valid Django BoundField.')
bootstrap3.exceptions.BootstrapError: Parameter "field" should contain a valid Django BoundField.
2018-11-07 20:53:57 [basehttp ERROR] "GET /sqlaudits/masteruser/create/ HTTP/1.1" 500 173656
2018-11-07 20:59:07 [basehttp INFO] "GET /sqlaudits/masteruser/ HTTP/1.1" 200 22022
2018-11-07 20:59:07 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:59:07 [basehttp INFO] "GET /static/img/facio.ico HTTP/1.1" 200 1744
2018-11-07 20:59:10 [basehttp INFO] "GET /sqlaudits/masterschema/ HTTP/1.1" 200 22028
2018-11-07 20:59:10 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 20:59:13 [log ERROR] Internal Server Error: /sqlaudits/masterschema/create/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 516, in bootstrap_field
    return render_field(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/forms.py", line 69, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/renderers.py", line 248, in __init__
    raise BootstrapError('Parameter "field" should contain a valid Django BoundField.')
bootstrap3.exceptions.BootstrapError: Parameter "field" should contain a valid Django BoundField.
2018-11-07 20:59:13 [basehttp ERROR] "GET /sqlaudits/masterschema/create/ HTTP/1.1" 500 172275
2018-11-07 21:03:29 [log ERROR] Internal Server Error: /sqlaudits/masterschema/create/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 516, in bootstrap_field
    return render_field(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/forms.py", line 69, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/renderers.py", line 248, in __init__
    raise BootstrapError('Parameter "field" should contain a valid Django BoundField.')
bootstrap3.exceptions.BootstrapError: Parameter "field" should contain a valid Django BoundField.
2018-11-07 21:03:29 [basehttp ERROR] "GET /sqlaudits/masterschema/create/ HTTP/1.1" 500 172410
2018-11-07 21:03:36 [basehttp INFO] "GET /sqlaudits/masterprivilege/ HTTP/1.1" 200 22035
2018-11-07 21:03:36 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 21:03:38 [log ERROR] Internal Server Error: /sqlaudits/masternetwork/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/urls/base.py", line 75, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'api-sqlautids'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/urls/base.py", line 86, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'api-sqlautids' is not a registered namespace
2018-11-07 21:03:38 [basehttp ERROR] "GET /sqlaudits/masternetwork/ HTTP/1.1" 500 202673
2018-11-07 21:04:16 [basehttp INFO] "GET /sqlaudits/masternetwork/ HTTP/1.1" 200 21918
2018-11-07 21:04:16 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 21:04:17 [log ERROR] Internal Server Error: /api/sqlaudits/v1/masternetwork/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/generics.py", line 152, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 90, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 31, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 73, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/filterset.py", line 71, in __new__
    new_class.base_filters = new_class.get_filters()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: username, master_host, master_user
2018-11-07 21:04:17 [basehttp ERROR] "GET /api/sqlaudits/v1/masternetwork/?_=1541595856848 HTTP/1.1" 500 22275
2018-11-07 21:04:57 [basehttp INFO] "GET /sqlaudits/masternetwork/ HTTP/1.1" 200 21921
2018-11-07 21:04:57 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 21:04:58 [basehttp INFO] "GET /static/img/facio.ico HTTP/1.1" 200 1744
2018-11-07 21:04:58 [log ERROR] Internal Server Error: /api/sqlaudits/v1/masternetwork/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/generics.py", line 152, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 90, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 31, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 73, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/filterset.py", line 71, in __new__
    new_class.base_filters = new_class.get_filters()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: username, master_host, master_user
2018-11-07 21:04:58 [basehttp ERROR] "GET /api/sqlaudits/v1/masternetwork/?_=1541595897698 HTTP/1.1" 500 22275
2018-11-07 21:05:01 [log ERROR] Internal Server Error: /sqlaudits/masternetwork/create/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/views/generic/edit.py", line 168, in get
    return super().get(request, *args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/home/chenwh/project/sqlaudit/sqlaudits/views/masternetwork.py", line 74, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/views/generic/edit.py", line 66, in get_context_data
    kwargs['form'] = self.get_form()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/views/generic/edit.py", line 33, in get_form
    return form_class(**self.get_form_kwargs())
  File "/home/chenwh/project/sqlaudit/sqlaudits/forms.py", line 57, in __init__
    super(MasterConfigCreateUpdateForm, self).__init__(*args, **kwargs)
TypeError: super(type, obj): obj must be an instance or subtype of type
2018-11-07 21:05:01 [basehttp ERROR] "GET /sqlaudits/masternetwork/create/ HTTP/1.1" 500 119285
2018-11-07 21:06:01 [signals_handler DEBUG] Receive django ready signal
2018-11-07 21:06:01 [signals_handler DEBUG]   - fresh all settings
2018-11-07 21:06:05 [log ERROR] Internal Server Error: /sqlaudits/masternetwork/create/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 516, in bootstrap_field
    return render_field(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/forms.py", line 69, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/renderers.py", line 248, in __init__
    raise BootstrapError('Parameter "field" should contain a valid Django BoundField.')
bootstrap3.exceptions.BootstrapError: Parameter "field" should contain a valid Django BoundField.
2018-11-07 21:06:05 [basehttp ERROR] "GET /sqlaudits/masternetwork/create/ HTTP/1.1" 500 173350
2018-11-07 21:06:23 [signals_handler DEBUG] Receive django ready signal
2018-11-07 21:06:23 [signals_handler DEBUG]   - fresh all settings
2018-11-07 21:06:25 [signals_handler DEBUG] Receive django ready signal
2018-11-07 21:06:25 [signals_handler DEBUG]   - fresh all settings
2018-11-07 21:06:36 [log ERROR] Internal Server Error: /sqlaudits/masternetwork/create/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 516, in bootstrap_field
    return render_field(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/forms.py", line 69, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/renderers.py", line 248, in __init__
    raise BootstrapError('Parameter "field" should contain a valid Django BoundField.')
bootstrap3.exceptions.BootstrapError: Parameter "field" should contain a valid Django BoundField.
2018-11-07 21:06:36 [basehttp ERROR] "GET /sqlaudits/masternetwork/create/ HTTP/1.1" 500 173350
2018-11-07 22:17:06 [log ERROR] Internal Server Error: /sqlaudits/masternetwork/create/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 516, in bootstrap_field
    return render_field(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/forms.py", line 69, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/renderers.py", line 248, in __init__
    raise BootstrapError('Parameter "field" should contain a valid Django BoundField.')
bootstrap3.exceptions.BootstrapError: Parameter "field" should contain a valid Django BoundField.
2018-11-07 22:17:06 [basehttp ERROR] "GET /sqlaudits/masternetwork/create/ HTTP/1.1" 500 173350
2018-11-07 22:18:19 [log ERROR] Internal Server Error: /sqlaudits/masternetwork/create/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 516, in bootstrap_field
    return render_field(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/forms.py", line 69, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/renderers.py", line 248, in __init__
    raise BootstrapError('Parameter "field" should contain a valid Django BoundField.')
bootstrap3.exceptions.BootstrapError: Parameter "field" should contain a valid Django BoundField.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/context.py", line 208, in push_state
    yield
SystemError: error return without exception set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/context.py", line 250, in bind_template
    yield
SystemError: error return without exception set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/context.py", line 208, in push_state
    yield
SystemError: error return without exception set
2018-11-07 22:18:19 [basehttp ERROR] "GET /sqlaudits/masternetwork/create/ HTTP/1.1" 500 215584
2018-11-07 22:18:41 [signals_handler DEBUG] Receive django ready signal
2018-11-07 22:18:41 [signals_handler DEBUG]   - fresh all settings
2018-11-07 22:18:43 [signals_handler DEBUG] Receive django ready signal
2018-11-07 22:18:43 [signals_handler DEBUG]   - fresh all settings
2018-11-07 22:18:48 [log ERROR] Internal Server Error: /sqlaudits/masternetwork/create/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 516, in bootstrap_field
    return render_field(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/forms.py", line 69, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/bootstrap3/renderers.py", line 248, in __init__
    raise BootstrapError('Parameter "field" should contain a valid Django BoundField.')
bootstrap3.exceptions.BootstrapError: Parameter "field" should contain a valid Django BoundField.
2018-11-07 22:18:48 [basehttp ERROR] "GET /sqlaudits/masternetwork/create/ HTTP/1.1" 500 173350
2018-11-07 22:19:07 [log ERROR] Internal Server Error: /api/sqlaudits/v1/masternetwork/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/viewsets.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/rest_framework/generics.py", line 152, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 90, in filter_queryset
    filterset = self.get_filterset(request, queryset, view)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 31, in get_filterset
    filterset_class = self.get_filterset_class(view, queryset)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/rest_framework/backends.py", line 73, in get_filterset_class
    class AutoFilterSet(self.filterset_base):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/filterset.py", line 71, in __new__
    new_class.base_filters = new_class.get_filters()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django_filters/filterset.py", line 352, in get_filters
    "%s" % ', '.join(undefined)
TypeError: 'Meta.fields' contains fields that are not defined on this FilterSet: username, master_host, master_user
2018-11-07 22:19:07 [basehttp ERROR] "GET /api/sqlaudits/v1/masternetwork/?_=1541600347235 HTTP/1.1" 500 22275
2018-11-07 22:19:12 [log ERROR] Internal Server Error: /sqlaudits/masterschema/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'masterschena-list' not found. 'masterschena-list' is not a valid view function or pattern name.
2018-11-07 22:19:12 [basehttp ERROR] "GET /sqlaudits/masterschema/ HTTP/1.1" 500 195573
2018-11-07 22:19:46 [log ERROR] Internal Server Error: /sqlaudits/masterschema/
Traceback (most recent call last):
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
    response = response.render()
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/template/defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/chenwh/project/venvjumpserver/lib/python3.6/site-packages/django/urls/resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'masterschena-list' not found. 'masterschena-list' is not a valid view function or pattern name.
2018-11-07 22:19:46 [basehttp ERROR] "GET /sqlaudits/masterschema/ HTTP/1.1" 500 195707
2018-11-07 22:20:11 [basehttp INFO] "GET /sqlaudits/masterschema/ HTTP/1.1" 200 21977
2018-11-07 22:20:11 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 22:20:13 [basehttp INFO] "GET /sqlaudits/masterschema/create/ HTTP/1.1" 200 12408
2018-11-07 22:20:13 [basehttp INFO] "GET /zh/jsi18n/ HTTP/1.1" 200 3333
2018-11-07 22:47:09 [signals_handler DEBUG] Receive django ready signal
2018-11-07 22:47:09 [signals_handler DEBUG]   - fresh all settings
2018-11-07 22:47:12 [signals_handler DEBUG] Receive django ready signal
2018-11-07 22:47:12 [signals_handler DEBUG]   - fresh all settings
2018-11-07 22:49:20 [signals_handler DEBUG] Receive django ready signal
2018-11-07 22:49:20 [signals_handler DEBUG]   - fresh all settings
2018-11-07 22:49:22 [signals_handler DEBUG] Receive django ready signal
2018-11-07 22:49:22 [signals_handler DEBUG]   - fresh all settings
2018-11-07 22:52:32 [signals_handler DEBUG] Receive django ready signal
2018-11-07 22:52:32 [signals_handler DEBUG]   - fresh all settings
2018-11-07 22:52:34 [signals_handler DEBUG] Receive django ready signal
2018-11-07 22:52:34 [signals_handler DEBUG]   - fresh all settings
2018-11-07 22:56:02 [signals_handler DEBUG] Receive django ready signal
2018-11-07 22:56:02 [signals_handler DEBUG]   - fresh all settings
2018-11-07 22:56:04 [signals_handler DEBUG] Receive django ready signal
2018-11-07 22:56:04 [signals_handler DEBUG]   - fresh all settings
2018-11-07 23:50:17 [signals_handler DEBUG] Receive django ready signal
2018-11-07 23:50:17 [signals_handler DEBUG]   - fresh all settings
2018-11-07 23:50:20 [signals_handler DEBUG] Receive django ready signal
2018-11-07 23:50:20 [signals_handler DEBUG]   - fresh all settings
2018-11-07 23:53:36 [signals_handler DEBUG] Receive django ready signal
2018-11-07 23:53:36 [signals_handler DEBUG]   - fresh all settings
2018-11-07 23:53:39 [signals_handler DEBUG] Receive django ready signal
2018-11-07 23:53:39 [signals_handler DEBUG]   - fresh all settings
2018-11-07 23:54:42 [signals_handler DEBUG] Receive django ready signal
2018-11-07 23:54:42 [signals_handler DEBUG]   - fresh all settings
2018-11-07 23:54:45 [signals_handler DEBUG] Receive django ready signal
2018-11-07 23:54:45 [signals_handler DEBUG]   - fresh all settings
2018-11-07 23:55:24 [signals_handler DEBUG] Receive django ready signal
2018-11-07 23:55:24 [signals_handler DEBUG]   - fresh all settings
2018-11-07 23:55:26 [signals_handler DEBUG] Receive django ready signal
2018-11-07 23:55:26 [signals_handler DEBUG]   - fresh all settings
